language: csharp
branches:
  only:
  - dev
dist: trusty
mono: none
dotnet: 2.1.301
os:
- linux
- osx
addons:
  apt:
    packages:
    - libunwind8
    - maven
script:
- "./build.sh --ci /p:BuildNumber=$((10000+TRAVIS_BUILD_NUMBER))"
